app/urls.py
from django.urls import path
from . import views
from django.contrib.auth.decorators import login_required


urlpatterns = [
    path('', views.Home.as_view(), name="home"),
    path('register/',views.Register.as_view(), name='register'),
    path('teacher_signup/',views.teacher_signup.as_view(), name='teacher_signup'),
    path('student_signup/',views.student_signup.as_view(), name='student_signup'),
    path('login/',views.login_request, name='login'),
    path('logout/',views.logout_view, name='logout'),

    path('teachers/', views.TeacherProfile.as_view(), name="teachers_profile"),
    path('students/', views.StudentsProfile.as_view(), name="students_profile"),

    path('courses/', views.Course_list.as_view(), name='courses'),
    path('courses/<int:pk>/', views.CourseDetail.as_view(), name="course_detail"),

    path('courses/<int:pk>/lessons/add/', views.LessonCreate.as_view(), name="lesson_create"),
    path('lesson/<int:pk>/', views.Lesson_detail.as_view(), name="lesson_detail"),
    path('lesson/<int:pk>/edit/', views.LessonEdit.as_view(), name="lesson_edit"),
    path('lesson/<int:pk>/delete', views.LessonDelete.as_view(), name="lesson_delete"),
    
    path('class/', views.ClassRoom.as_view(), name='class'),

    path('courses/<int:pk>/labs/add', views.LabCreate.as_view(), name="lab_create"),
    path('lab/<int:pk>/', views.Lab_detail.as_view(), name="lab_detail"),
    path('lab/<int:pk>/edit/', views.LabEdit.as_view(), name="lab_edit"),
    path('lab/<int:pk>/delete', views.LabDelete.as_view(), name="lab_delete"),

    path('lab/<int:pk>/deliverable',views.DeliverableCreate.as_view(), name="deliverable_create"),
    path('deliverable/', views.DeliverablePage.as_view(), name='deliverable'),
    path('deliverable/<int:pk>/', views.Deliverable_detail.as_view(), name="deliverable_detail"),

    path('lesson/<int:pk>/comment',views.CommentCreate.as_view(), name="comment_create"),
    path('lesson/<int:pk>/comment_edit',views.CommentEdit.as_view(), name="comment_edit"),
    path('lesson/<int:pk>/comment_delete',views.CommentDelete.as_view(), name="comment_delete"),

    path('library/', views.BooksList.as_view(), name='library'),
    path('book/add', views.BookCreate.as_view(), name="book_create"),
    path('book/<int:pk>/delete',views.BookDelete.as_view(), name="book_delete"),



]

teacher_student/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls'))
]

app/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.deletion import CASCADE
# Create your models here.


class User(AbstractUser):
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)
    first_name = models.CharField(max_length=100)
    last_name = models.CharField(max_length=100)

    def __str__(self):
        return self.username


class Teacher(models.Model):

    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)
    img = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.user


class Student(models.Model):

    user = models.OneToOneField(
        User, on_delete=models.CASCADE, primary_key=True)
    img = models.CharField(max_length=250)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user


class Course(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100)
    image = models.CharField(max_length=1000)
    description = models.CharField(max_length=9999)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    # students = models.ManyToManyField(Student)
    # teachers = models.ManyToManyField(Teacher)

    def __str__(self):
        return self.name


class Lesson(models.Model):
    id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=250)
    description = models.CharField(max_length=9999)
    course = models.ForeignKey(
        Course, on_delete=models.CASCADE, related_name="lessons")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['created_at']


class Lab(models.Model):
    LAB_TYPES = (
        ('Lab', 'Lab'),
        ('Homework', 'Homework'),
        ('Project', 'Project'),
    )
    id = models.AutoField(primary_key=True)
    types = models.CharField(max_length=20, choices=LAB_TYPES)
    title = models.CharField(max_length=250)
    description = models.CharField(max_length=9999)
    course = models.ForeignKey(
        Course, on_delete=models.CASCADE, related_name="labs")
    lab_deliverable = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['created_at']


class Deliverable(models.Model):
    id = models.AutoField(primary_key=True)
    lab = models.ForeignKey(Lab, on_delete=models.CASCADE,
                            related_name="deliverables")
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="deliverables")
    title = models.CharField(max_length=250)
    description = models.CharField(max_length=9999)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title
     

    class Meta:
        ordering = ['created_at']

class Comment(models.Model):
    comment = models.CharField(max_length=200)
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name="comments")
    lesson = models.ForeignKey(Lesson, on_delete=CASCADE, related_name="comments")
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


    def __str__(self):
        return self.comment

    class Meta:
        ordering = ['created_at'] 

class Book(models.Model):
    title = models.CharField(max_length=250)
    img = models.CharField(max_length=1000)
    author = models.CharField(max_length=100)
    description = models.CharField(max_length=9999)
    link = models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['title']     

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'styles/main.css' %}" />
    <script src="{% static 'scripts/main.js' %}" defer></script>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <title>Teachers VS Students</title>
</head>

<body>
  <style>
    @import url('https://fonts.googleapis.com/css2?family=Shadows+Into+Light&display=swap');
    </style>
  
    <nav class="navbar navbar-expand-lg navbar-light bg-secondary text-uppercase "  >
        <div class="container">
         <a class="navbar-brand " href="/" style="font-family: 'Shadows Into Light', cursive;"> Teachers <span style="color:red;"> VS </span> Students </a>
          {% if user.is_authenticated %}
          <a class="navbar-brand">{{user.username}}</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
             Menu 
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent" aria-expanded="false">
            <ul class="navbar-nav ml-auto " >
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" style="color: azure;" href="/">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/class">Class</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/courses">courses</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="/library">Library</a>
              </li>
              {% if user.is_teacher %}
              <li class="nav-item">
                <a class="nav-link" href="/teachers">Profile</a>
              </li>
              {% else %}
              <li class="nav-item">
                <a class="nav-link" href="/students">Profile</a>
              </li>

                {% endif %}
              
              <li class="nav-item">
                <a class="nav-link" href="{% url 'logout' %}">Logout</a>
              </li>
    
            </ul>
            
          
          {% else %}
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ml-auto">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'register' %}">Register</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'login' %}">Login</a>
              </li>
    
            </ul>
          </div>
          </div>
          {% endif %}
        </div>
    </nav>
    <div >
        {% block content %}{% endblock %}
    </div>


    

  <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  <!-- JavaScript Bundle with Popper -->
  <!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LR+8nbTov4+1p" crossorigin="anonymous"></script> -->

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js"
  integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>

</body>

</html>

app/templates/book_create.html
{% extends 'base.html' %} {% block content %}
<h1>Add a Book</h1>

<form method="post">

  {% csrf_token %} 

  {{form.as_p}} 

  <input type="submit" value="Submit" />
</form>

{% endblock %}

app/templates/class.html
{% extends 'base.html' %} {% block content %}
<style>
  @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap');
  @import url('https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Montserrat:wght@500&display=swap');

  body {
    background-image: url("../static/images/bg6.jpg");
    height: 100%;

    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;
  }

  p {
    color: black;
    font-family: 'Montserrat', sans-serif;
  }

  .card {
    margin: 0 auto;
    float: none;
    margin-bottom: 10px;
   
  }
</style>
<div style="display: flex; justify-content: center;">
  <img class="fw-light" src="../static/images/logo3.png" style="width: 170px; padding-top: 0%; ">
</div>
<h1 style="text-align: center; font-family: 'Abril Fatface', cursive; padding-top: 0%; font-size: 80px;">Class Room</h1>
<h6 style="text-align: center;"> Every Lessons and Labs are Here!</h6>




<div class="row justify-content-center">

  {% for lesson in lessons %}
  <a href="{% url 'lesson_detail' lesson.pk %}" style="text-decoration: none;">
    <div class="card center" style="width: 70rem; padding: 20px; margin: 20px; background:#cbcdccc6;">
      <h5 class="card-header" style="color: black;">{{lesson.course}}</h5>

      <div class="card-body">
        <h5 class="card-title" style="color: black;">{{lesson.title}}</h5>
        <p class="card-text ">{{lesson.description}}</p>
      </div>
      <div class="card-footer" style="background-color: #e1e1e1cf;">
        {% for comment in lesson.comments.all %}
        <p>
          <span class="font-weight-bold">{{ comment.author }} &middot;</span>
          {{ comment }}
        </p>
        {% if user.id == comment.author.id %}
        <a href="{% url 'comment_edit' comment.pk %}">Edit</a>
        <a style="cursor: pointer; color: red;" href="{% url 'comment_delete' comment.pk %}">Delete </a>
        {% endif %}
        {% endfor %}
        <br></br>
        <a href="{% url 'comment_create' lesson.pk %}" >+ New Comment</a>
      </div>
    </div>
  </a>
  {% endfor %}
</div>
<div class="row justify-content-center">
  {% for lab in labs %}
  <a href="{% url 'lab_detail' lab.pk %}" style="text-decoration: none;">
    <div class="card center" style="width: 70rem; padding: 20px; margin: 20px; background:#c4bf9bba;">
      <h5 class="card-header" style="color: black;">{{lab.types}}</h5>

      <div class="card-body">
        <h5 class="card-title" style="color: black;">{{lab.course}}</h5>
        <h5 class="card-title" style="color: black;">{{lab.title}}</h5>
        <p class="card-text ">{{lab.description}}</p>
        {% if lab.lab_deliverable %}
        <p class="card-text">Deliverable</p>
        {% endif %}
      </div>
    </div>
  </a>
  {% endfor %}
</div>

{% endblock %}

app/templates/comment_edit.html
{% extends 'base.html' %}

{% block content %}
<style>
   
    body {
  
        background-color: rgba(255, 232, 174, 0.892);
    }
  </style>
    <h1 style="text-align: center;   padding-top: 0%; font-size: 30px;">Edit comment</h1>
    <form method="post" style="text-align: center;">
        {% csrf_token %}
        {{ form }}
        <button class="btn btn-info" type="submit">Add Comment</button>
    </form>
{% endblock  %}

app/templates/course_detail.html
{% extends 'base.html' %} {% block content %}

<style>
    @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Montserrat:wght@500&display=swap');

    body {

        background-image: linear-gradient(rgba(255, 232, 174, 0.892), rgba(106, 164, 250, 0.81));
    }
</style>


<h1 style="text-align: center; font-family: 'Abril Fatface', cursive; padding-top: 0%; font-size: 80px;">
    {{course.name}}</h1>




<img style='
height: auto;
width: auto;
max-height: 250px;
max-width: 50%;
display: block;
margin-left: auto;
margin-right: auto;
border-radius: 5px;
' src="{{course.image}}" />
<br />
<p style="
text-align: center;
background: rgba(93, 67, 46, 0);
border-radius: 5px;

">
    {{course.description}}
</p>
{% if user.is_teacher %}
<div style="font-family: Abril Fatface; position: center; text-align: center;">
    <a action="{% url 'lesson_create' course.pk %}" style="padding-right: 15px; cursor: pointer; font-size: 20px;"
        data-toggle="modal" data-target="#staticBackdrop">
        Add Lesson
    </a>
    <a action="{% url 'lab_create' course.pk %}" style="cursor: pointer; font-size: 20px;" data-toggle="modal"
        data-target="#staticBackdrop2">
        Add Lab
    </a>
</div>
{% endif %}

<div class="row justify-content-center">
    {% for lesson in course.lessons.all %}


    <a href="{% url 'lesson_detail' lesson.pk %}" style="text-decoration: none;">

        <div class="card center" style="width: 70rem; padding: 20px; margin: 20px; background:#cbcdccc6;">
            <h5 class="card-header" style="color: black;">{{lesson.course}}</h5>

            <div class="card-body">
                <h5 class="card-title" style="color: black;">{{lesson.title}}</h5>
                <p class="card-text ">{{lesson.description}}</p>
            </div>
            {% if user.is_teacher %}
            <a href="{% url 'lesson_edit' lesson.pk %}">Edit</a><br>
            <a href="{% url 'lesson_delete' lesson.pk %}">Delete</a>
            {% endif %}

        </div>
    </a>
    {% empty %}
    <div class="card-body">

        <p class="card-text">No Lessons </p>

    </div>
    </a>
</div>
</div>

{% endfor %}

{% for lab in course.labs.all %}
<a href="{% url 'lab_detail' lab.pk %}" style="text-decoration: none;">
    <div class="card anchor" style="width: 70rem; padding: 20px; margin: 20px; background:#c4bf9bba;">
        <h5 class="card-title" style="color: black;">{{lab.types}}</h5>

        <div class="card-body">
            <h5 class="card-title" style="color: black;">{{lab.course}}</h5>
            <h5 class="card-title" style="color: black;">{{lab.title}}</h5>
            <p class="card-text ">{{lab.description}}</p>
            {% if lab.lab_deliverable %}
            <p class="card-text">Deliverable</p>
            {% endif %}
        </div>
    </div>
</a>
{% empty %}
    <div class="card-body">

        <p class="card-text">No Labs </p>

    </div>
{% endfor %}


<div class="modal fade" id="staticBackdrop" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" >
        <div class="modal-content" style="background: rgba(231, 232, 213, 0.899);">
            <div class="modal-header" >
                <h5 class="modal-title" id="staticBackdropLabel">Add A New Lesson</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form class="mb-5" action="{% url 'lesson_create' course.pk %}" method="post">
                    {% csrf_token %}
                    
                        <div class="form-group">
                            <label for="title-name" class="col-form-label">Title:</label>
                            <input class="form-control" type="text" name="title" id="title-name" placeholder="Title" required />
                        </div>
                        <div class="form-group">
                            <label for="description-text" class="col-form-label">Description:</label>
                            <textarea class="form-control" type="description" id="description-text" name="description"
                                placeholder="description"></textarea>
                        </div>
                        <div class="control">
                            <input class="button is-primary" type="submit" value="Add Lesson" />
                        </div>
                    
                </form>
                
            </div>
        </div>
    </div>
</div>

</div>
</div>

</div>


<div class="modal fade" id="staticBackdrop2" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel"
    aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg">
        <div class="modal-content" style="background: rgba(215, 216, 186, 0.89);">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Add A New Lab</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form class="mb-5" action="{% url 'lab_create' course.pk %}" method="post">
                    {% csrf_token %}
                   
                        <div class="dropdown">
                            <label for="id_types" class="col-form-label">Lab Types:</label>
                            <select name="types" required id="id_types">
                                <option value selected>---------</option>
                                <option value="Lab">lab</option>
                                <option value="Homework">Homework</option>
                                <option value="Project">Project</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label for="title-name" class="col-form-label">Title:</label>
                            <input class="form-control" type="text" name="title" id="title-name" placeholder="Title" required />
                        </div>
                        <div class="form-group">
                            <label for="description-text" class="col-form-label">Description:</label>
                            <textarea class="form-control" type="description" name="description" id="description-text" placeholder="description"
                                required ></textarea>
                        </div>
  
                        <div class="form-check">
                            
                            <input class="form-check-input" type="checkbox" name="lab_deliverable" id="deliverable" default="false" />
                            <label class="form-check-label" for="deliverable">Lab Deliverable</label>
                        </div>
                        <div class="control">
                            <input class="button is-primary" type="submit" value="Add lab" />
                        </div>
                   
                </form>
               
            </div>
        </div>
    </div>
</div>

</div>
</div>


</div>




{% endblock %}

app/templates/course_list.html
{% extends 'base.html' %} {% block content %}


<style>
  @import url('https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Montserrat:wght@500&display=swap');
    body {
       background-image: url("../static/images/bg6.jpg");
       height: 100%;
     
       background-position: center;
       background-repeat: no-repeat;
       background-size: cover;
   }
   p {
      display: -webkit-box;
      -webkit-box-orient: vertical;
      -webkit-line-clamp: 3;
      overflow: hidden;
    }
  
</style>
<div style="display: flex; justify-content: center;">
  <img class="fw-light" src="../static/images/logo3.png" style="width: 180px; padding-top: 0%; "></div>
<h1 style="text-align: center; font-family: 'Abril Fatface', cursive; padding-top: 0%; font-size: 80px;">Coruses</h1>


<div class="row" style="color: transparent;">

    {% for course in courses %}
    <a href="{% url 'course_detail' course.pk %}" style="text-decoration: none;">
      <div class="card anchor "
        style="width: 20rem; padding: 20px; margin: 20px; background:#525251b5;">
        <img src="{{course.image}}" class="card-img-top" alt="{{course.name}}">
        <div class="card-body">
          <h5 class="card-title" style="color: rgb(228, 228, 228);">{{course.name}}</h5>
          <p class="card-text " style="color: rgb(228, 228, 228);">{{course.description}}</p>
        </div>
      </div>
    </a>

    {% endfor %}

  </div>

{% endblock %}

app/templates/deliverable_detail.html
{% extends 'base.html' %} {% block content %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Montserrat:wght@500&display=swap');

    body {
        background-image: linear-gradient(rgba(255, 232, 174, 0.892), rgba(106, 164, 250, 0.81));

    }

    p {
        color: black;
        font-family: 'Montserrat', sans-serif;
    }

   
</style>
<div class="card-body">

    <h5 class="card-title"
        style="text-align: center; font-family: 'Abril Fatface', cursive; padding-top: 0%; font-size: 80px;">
        {{deliverable.lab}}</h5>
    <h5
        style="text-align: center; text-decoration: underline; font-family: 'Montserrat'; color: rgba(0, 18, 18, 0.571);">
        By </h5>
    <h5 class="user-name" style="text-align: center;">{{deliverable.user}} </h5>
   
    <h5
        style="text-align: center; text-decoration: underline; font-family: 'Montserrat'; color: rgba(0, 18, 18, 0.571);">
        Title </h5>
    <h5 class="user-name" style="text-align: center;">{{deliverable.title}} </h5>
    <h5
        style="text-align: center; text-decoration: underline; font-family: 'Montserrat'; color: rgba(0, 18, 18, 0.571);">
        Description</h5>
    <h5 class="card-text" style="text-align: center;">{{deliverable.description}}</h5>
    
</div>

{% endblock %}

app/templates/deliverables.html
{% extends 'base.html' %} {% block content %}
<style>
    @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap');
    @import url('https://fonts.googleapis.com/css2?family=Abril+Fatface&family=Montserrat:wght@500&display=swap');
   
    body {
       background-image: url("../static/images/bg6.jpg");
       height: 100%;
     
       background-position: center;
       background-repeat: no-repeat;
       background-size: cover;
   }
   p {
     color: black;
     font-family: 'Montserrat', sans-serif;
   }
   .card {
          margin: 0 auto; /* Added */
          float: none; /* Added */
          margin-bottom: 10px; /* Added */
  }
   </style>
   <div style="display: flex; justify-content: center;">
   <img class="fw-light" src="../static/images/logo3.png" style="width: 170px; padding-top: 0%; "></div>
  <h1 style="text-align: center; font-family: 'Abril Fatface', cursive; padding-top: 0%; font-size: 80px;">Deliverables</h1>
  


  <div class="row justify-content-center" >
    {% for deliverable in deliverables %}
    <a href="{% url 'deliverable_detail' deliverable.pk %}" style="text-decoration: none;">
        
        <div class="card center"
            style="width: 70rem; padding: 20px; margin: 20px; background:#cbcdccc6;">
            <h5 class="card-header" style="color: black;">{{deliverable.lab}}</h5>    
            <div class="card-body">
                <h5 class="card-title" style="color: black;">{{deliverable.title}}</h5>
                <p class="card-text ">{{deliverable.description}}</p>
                <p class="card-text ">BY: {{deliverable.user}}</p>
            </div>
        </div>
    </a>
    {% endfor %}
</div>
{% endblock %}

app/templates/home.html
{% extends 'base.html' %} {% block content %}


<style>
  @import url('https://fonts.googleapis.com/css2?family=Montserrat:wght@500&display=swap');
 body {
    background-image: url("../static/images/bg6.jpg");
    height: 100%;
  
    background-position: center;
    background-repeat: no-repeat;
    background-size: cover;

 }
</style>
<main>
    <section class="py-5 text-center container">
        <div class="row py-lg-5">
          <div class="col-lg-6 col-md-8 mx-auto">
   
            <img class="fw-light" src="../static/images/logo3.png" style="width: 250px; padding-top: 0%;">
            <p class="lead text-muted">Teachers vs Students is the best App that is designed to manage and simplify the day-to-day communication between students and teachers.Teachers can more easily input, manage, and access  data. And students can easily access, deliver and engage with their teachers and other students. In order to get started Register below.</p>
            <p>
              
              <a href="{% url 'register' %}" class="btn btn-primary my-2">Register Here</a>
              <a href="{% url 'login' %}" class="btn btn-secondary my-2">Login</a>
              
            </p>
          </div>
        </div>
      </section>
<div>
     <h1 style="text-align: center; font-family: 'Montserrat';">Different courses</h1>
    <div class="row" style="color: transparent;">
        {% for course in courses %}
       
          <div class="card anchor "
            style="width: 16rem; padding: 20px; margin: 20px; background:#7d746592;">
            <img src="{{course.image}}" style="height: 16rem;"class="card-img-top" alt="{{course.name}}">
            <div class="card-body">
              <h5 class="card-title" style="color: black;">{{course.name}}</h5>
              
            </div>
          </div>
      
    
        {% endfor %}
    
      </div>
</main>
{% endblock %}

app/templates/lab_create.html
{% extends 'base.html' %} {% block content %}

<h1>Add a Car Model</h1>

<form method="post">
    <!-- Security Feature  -->
      {% csrf_token %} 
    <!--  Generate inputs  -->
      {{form.as_p}} 
    <!--  Submit form  -->
      <input type="submit" value="Submit" />
    </form>
    
    {% endblock %}